using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using HRsystem.Models;
using System;
using System.Collections.Generic;


namespace HRsystem.Reports
{
    public class EmployeeReport : IDocument
    {
        public List<HREmployee> Employees { get; set; }

        public EmployeeReport(List<HREmployee> employees)
        {
            Employees = employees;
        }

        public void Compose(IDocumentContainer container)
        {
            int rowsPerPage = 15; // adjust based on row height and page size
            int totalRows = Employees.Count;

            for (int pageIndex = 0; pageIndex < Math.Ceiling(totalRows / (double)rowsPerPage); pageIndex++)
            {
                var pageEmployees = Employees.Skip(pageIndex * rowsPerPage).Take(rowsPerPage).ToList();

                container.Page(page =>
                {
                    page.Size(PageSizes.A4.Landscape());
                    page.Margin(20);
                    page.DefaultTextStyle(x => x
                        .FontSize(9)
                        .FontColor(Colors.Black)
                    );

                    page.Header().ShowOnce().AlignCenter()
                        .Text(text => text.Span("كشف بجميع الموظفين من 2026-01 الي 2026-02").Bold().FontSize(16));

                    page.Content().Padding(5)
                        .ContentFromRightToLeft()
                        .Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                for (int i = 0; i < 12; i++) columns.RelativeColumn();
                            });

                            // Header row
                            string[] headers = { "اسم الموظف", "الرقم القومي", "رقم الهاتف", "الحالة الاجتماعية",
                    "الدين", "تاريخ الميلاد", "رقم التأمين", "تاريخ التعيين",
                    "تاريخ نهاية الخدمة", "القسم", "الوظيفة", "نوع العقد" };

                            table.Header(header =>
                            {
                                foreach (var h in headers)
                                    header.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                        .Text(text => text.Span(h).Bold()));
                            });

                            // Data rows
                            foreach (var emp in pageEmployees)
                            {
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.Name));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.NationalId));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.PhoneNumber));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.MarriageStatus));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.Religion));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.DateOfBirth.ToString("yyyy-MM-dd")));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.InsuranceNumber ?? ""));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.HireDate.ToString("yyyy-MM-dd")));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.EndDate.HasValue ? emp.EndDate.Value.ToString("yyyy-MM-dd") : ""));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.Department));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.JobName));
                                table.Cell().Element(cell => cell.Border(1).Padding(3).AlignCenter().AlignMiddle()
                                    .Text(emp.ContractType));
                            }
                        });

                    page.Footer().AlignCenter().Text(text =>
                    {
                        text.Span("Generated by HR System ");
                        text.Span(DateTime.Now.ToString("g"));
                    });
                });
            }

        }

        public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
    }
}
