using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using HRsystem.Models;
using System;
using System.Collections.Generic;

namespace HRsystem.Reports
{
public class EmployeeReport : IDocument
{
    public List<HREmployee> Employees { get; set; }

    public EmployeeReport(List<HREmployee> employees)
    {
        Employees = employees;
    }

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(30);

            // Default text style
            page.DefaultTextStyle(x => x.FontSize(12).FontColor(Colors.Black));

            page.DefaultTextStyle(x =>
                x.FontSize(12)
                .FontColor(Colors.Black)
                .DirectionFromRightToLeft() // applies to all Text elements by default
            );

            page.Header()
                .Text("تقرير بالموظفين")
                .FontSize(20)
                .Bold()
                .AlignCenter();

            page.Content()
            .Padding(5) // optional padding
            .ContentFromRightToLeft() // <-- sets RTL for everything inside
                .Table(table =>
                {
                    // Define columns
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(); // Name
                        columns.RelativeColumn(); // Department
                        columns.RelativeColumn(); // NationalId
                    });

                    // Header row
                    table.Header(header =>
                    {
                        header.Cell().Element(cell => cell.Border(1).Padding(5).Text("اسم الموظف").Bold());
                        header.Cell().Element(cell => cell.Border(1).Padding(5).Text("القسم").Bold());
                        header.Cell().Element(cell => cell.Border(1).Padding(5).Text("الرقم القومي").Bold());
                    });

                    // Data rows
                    foreach (var emp in Employees)
                    {
                        table.Cell().Element(cell => cell.Border(1).Padding(5).Text(emp.Name));
                        table.Cell().Element(cell => cell.Border(1).Padding(5).Text(emp.Department));
                        table.Cell().Element(cell => cell.Border(1).Padding(5).Text(emp.NationalId));
                    }
                });

            page.Footer()
                .AlignCenter()
                .Text(text =>
                {
                    text.Span("Generated by HR System ");
                    text.Span(DateTime.Now.ToString("g"));
                });
        });
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
}
}